version: '3.8'

services:
  # The CDR Parser
  cdr-parser:
    build:
      context: ./CDR-Parser
    volumes:
      - /opt/billing/cdr:/opt/billing/cdr
      - /opt/billing/archive:/opt/billing/archive
      - ./db.properties:/app/db.properties

  # The Rating Engine
  rating-engine:
    build:
      context: ./Rating_Engine
    volumes:
      - ./db.properties:/app/db.properties
    
  # Aggregator & Reporter 
  
  billing-scheduler:
    build: 
      context: ./scheduler
    container_name: billing_scheduler
    volumes:
      - ./Aggregator/target/AggregationEngine-1.0-SNAPSHOT-jar-with-dependencies.jar:/app/Aggregator.jar
      - ./BillReporter/target/BillReporter-1.0-SNAPSHOT.jar:/app/BillReporter.jar
      - ./BillReporter/io.properties:/app/io.properties
      - ./db.properties:/app/db.properties 
      - /opt/billing/bills:/opt/billing/bills
    restart: always
