version: '3.8'

services:
  # 1. The Database
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: billing
    ports:
      - "5434:5432" # Allows you to still use pgAdmin/DBeaver from your host machine
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. The CDR Parser
  cdr-parser:
    build:
      context: ./CDR-Parser
    depends_on:
      - postgres-db
    volumes:
      # This maps folders on your host machine directly into the container!
      - /opt/billing/cdr:/opt/billing/cdr
      - /opt/billing/archive:/opt/billing/archive
      
      - ./db.properties:/app/db.properties

  # 3. The Rating Engine
  rating-engine:
    build:
      context: ./Rating_Engine
    depends_on:
      - postgres-db
    volumes:
    - ./db.properties:/app/db.properties

volumes:
  pgdata:
